import type { Leccion } from '../../../../types';

export const leccion: Leccion = {
  id: 'mn-05-01',
  titulo: 'Convertir entre tipos: int(), float() y str()',
  descripcion: 'Aprende a convertir datos entre diferentes tipos usando las funciones de conversión.',
  duracionMinutos: 10,
  conceptosClave: ['int()', 'float()', 'str()', 'conversión de tipos', 'type casting'],
  contenido: [
    { tipo: 'introduccion', texto: 'A veces tienes un número en formato texto y necesitas hacer cálculos con él, o viceversa. Python te da funciones para convertir entre tipos fácilmente.' },
    { tipo: 'explicacion', titulo: 'Convertir a entero con int()', texto: '`int()` convierte un valor a número entero. Puedes convertir strings numéricos o floats. Cuando conviertes un float, se trunca la parte decimal (no se redondea).' },
    { tipo: 'ejemplo', titulo: 'int() en acción', descripcion: 'Convirtiendo varios tipos a entero:', codigo: "print(int('42'))      # 42 (string a int)\nprint(int(3.14))      # 3 (float a int, trunca)\nprint(int(True))      # 1 (bool a int)\nprint(int(False))     # 0 (bool a int)" },
    { tipo: 'explicacion', titulo: 'Convertir a decimal con float()', texto: '`float()` convierte valores a números decimales. Puedes convertir strings con punto decimal o enteros.' },
    { tipo: 'ejemplo', titulo: 'float() en acción', descripcion: 'Convirtiendo a decimal:', codigo: "print(float('3.14'))  # 3.14\nprint(float(5))       # 5.0\nprint(float('10'))    # 10.0" },
    { tipo: 'explicacion', titulo: 'Convertir a string con str()', texto: '`str()` convierte cualquier valor a su representación como texto. Es útil para concatenar números con texto.' },
    { tipo: 'ejemplo', titulo: 'str() en acción', descripcion: 'Convirtiendo a texto:', codigo: 'edad = 25\nprint("Tengo " + str(edad) + " años")\n# Tengo 25 años' },
    { tipo: 'error-comun', titulo: 'Concatenar sin convertir', codigoMal: "print('El número es ' + 42)", problema: 'No puedes concatenar texto con números directamente sin convertirlos.', codigoBien: "print('El número es ' + str(42))", solucion: 'Usa str() para convertir números a texto antes de concatenar.' },
    { tipo: 'resumen', puntos: ['int() convierte a entero (trunca decimales)', 'float() convierte a decimal', 'str() convierte cualquier valor a texto', 'Los booleanos True=1 y False=0 como enteros'] },
  ],
  ejercicios: [
    {
      id: 'mn-05-01-01',
      titulo: 'str a int',
      descripcion: "Usa `int()` para convertir el string `'42'` a número entero.",
      starter: '# Convierte e imprime\n',
      pistas: ["print(int('42'))"],
      explicacion: "int() convierte un string numérico a entero.",
      solucionOficial: "print(int('42'))",
      validate: { type: 'output', expected: '42' },
    },
    {
      id: 'mn-05-01-02',
      titulo: 'int a str',
      descripcion: "Crea `x = 99`. Imprime: `'El número es ' + str(x)`",
      starter: 'x = 99\n# Convierte a string y concatena\n',
      pistas: ["print('El número es ' + str(x))"],
      explicacion: "str() convierte cualquier valor a string.",
      solucionOficial: "x = 99\nprint('El número es ' + str(x))",
      validate: { type: 'output', expected: 'El número es 99' },
    },
    {
      id: 'mn-05-01-03',
      titulo: 'float a int',
      descripcion: 'Usa `int(3.7)` para convertir el decimal a entero.',
      starter: '# Convierte 3.7 a entero\n',
      pistas: ["print(int(3.7))"],
      explicacion: "int() trunca la parte decimal, no redondea.",
      solucionOficial: 'print(int(3.7))',
      validate: { type: 'output', expected: '3' },
    },
  ],
  cuestionario: [
    {
      id: 'mn-05-01-q1',
      pregunta: "¿Qué imprime `print(int('10'))`?",
      opciones: ["'10'", '10', 'Error', '10.0'],
      correcta: 1,
      explicacion: "int('10') convierte el string '10' al entero 10.",
    },
    {
      id: 'mn-05-01-q2',
      pregunta: '¿Qué imprime `print(int(4.9))`?',
      opciones: ['4', '5', '4.9', 'Error'],
      correcta: 0,
      explicacion: 'int() trunca: int(4.9) = 4 (no redondea).',
    },
    {
      id: 'mn-05-01-q3',
      pregunta: '¿Por qué necesitas convertir un número a string para concatenarlo?',
      opciones: ['Porque + no funciona con números', 'Porque Python no mezcla tipos en concatenación', 'Porque los números no tienen representación textual', 'No es necesario'],
      correcta: 1,
      explicacion: 'Python requiere que los tipos coincidan para usar +. str() resuelve esto.',
    },
  ],
};
