import type { Leccion } from '../../../../types';

export const leccion: Leccion = {
  id: 'mn-05-03',
  titulo: 'Aplicaciones prácticas de conversión de tipos',
  descripcion: 'Aplica la conversión de tipos en situaciones reales como cálculos y procesamiento de datos.',
  duracionMinutos: 10,
  conceptosClave: ['conversión práctica', 'calcular con strings', 'suma con conversión', 'round con decimales'],
  contenido: [
    { tipo: 'introduccion', texto: 'La conversión de tipos es esencial cuando trabajas con datos del mundo real: archivos, formularios o APIs suelen darte texto que necesitas convertir para operar matemáticamente.' },
    { tipo: 'explicacion', titulo: 'Calcular con datos convertidos', texto: 'Cuando recibes datos como strings (por ejemplo, de un formulario), debes convertirlos a números antes de hacer operaciones matemáticas. Intentar sumar strings los concatenaría en lugar de sumarlos.' },
    { tipo: 'ejemplo', titulo: 'String + número', descripcion: 'La diferencia entre concatenar y sumar:', codigo: "precio = '9.99'\ncantidad = 2\nprint(float(precio) * cantidad)  # 19.98\nprint(precio + str(cantidad))    # 9.992 (concatena)" },
    { tipo: 'explicacion', titulo: 'Formatear resultados', texto: 'A menudo querrás controlar cuántos decimales se muestran. Puedes usar `round()` para redondear a la cantidad deseada de decimales.' },
    { tipo: 'ejemplo', titulo: 'Redondear resultados', descripcion: 'Controlando la precisión:', codigo: 'precio = 19.9875\nprint(round(precio, 2))       # 19.99\nprint(round(precio, 1))       # 20.0\nprint(round(precio))          # 20' },
    { tipo: 'explicacion', titulo: 'Verificar tipos antes de operar', texto: 'Usa `type()` para saber con qué tipo de dato estás trabajando. Es especialmente útil cuando no estás seguro del formato de tus datos.' },
    { tipo: 'ejemplo', titulo: 'Tipos distintos', descripcion: 'Identificando tipos:', codigo: "print(type('hola'))  # <class 'str'>\nprint(type(3.14))    # <class 'float'>\nprint(type(42))      # <class 'int'>\nprint(type(True))    # <class 'bool'>" },
    { tipo: 'resumen', puntos: ['Convierte strings a números antes de calcular', 'Usa round() para controlar decimales', 'type() ayuda a identificar tipos de datos', 'La conversión evita errores inesperados'] },
  ],
  ejercicios: [
    {
      id: 'mn-05-03-01',
      titulo: 'Suma con conversión',
      descripcion: "Convierte el string `'10'` a entero y súmale `5`. Imprime.",
      starter: '# Convierte e imprime\n',
      pistas: ["print(int('10') + 5)"],
      explicacion: "Debes convertir el string a int antes de sumar.",
      solucionOficial: "print(int('10') + 5)",
      validate: { type: 'output', expected: '15' },
    },
    {
      id: 'mn-05-03-02',
      titulo: 'Calcular con conversión',
      descripcion: "Crea `precio = '9.99'` (string). Convierte a `float` y multiplícalo por `2`.",
      starter: "precio = '9.99'\n# Convierte y multiplica\n",
      pistas: ["print(float(precio) * 2)"],
      explicacion: "float() convierte strings con decimales a números.",
      solucionOficial: "precio = '9.99'\nprint(float(precio) * 2)",
      validate: { type: 'output', expected: '19.98' },
    },
    {
      id: 'mn-05-03-03',
      titulo: 'round con decimales',
      descripcion: 'Usa `round(3.14159, 2)` para redondear a 2 decimales.',
      starter: '# Redondea\n',
      pistas: ["print(round(3.14159, 2))"],
      explicacion: "round(n, decimales) controla los decimales.",
      solucionOficial: 'print(round(3.14159, 2))',
      validate: { type: 'output', expected: '3.14' },
    },
  ],
  cuestionario: [
    {
      id: 'mn-05-03-q1',
      pregunta: "¿Qué imprime `print('5' + '3')`?",
      opciones: ['8', "'8'", "'53'", '53'],
      correcta: 3,
      explicacion: "+ con strings los concatena: '5' + '3' = '53'.",
    },
    {
      id: 'mn-05-03-q2',
      pregunta: "Si tienes `precio = '9.99'`, ¿cómo lo conviertes a número?",
      opciones: ['int(precio)', 'float(precio)', 'str(precio)', 'bool(precio)'],
      correcta: 1,
      explicacion: 'Se necesita float() porque el string tiene punto decimal.',
    },
    {
      id: 'mn-05-03-q3',
      pregunta: '¿Qué imprime `print(round(2.5))`?',
      opciones: ['2', '3', '2.5', 'Error'],
      correcta: 0,
      explicacion: 'En Python 3, round(2.5) redondea al par más cercano: 2.',
    },
  ],
};
