import type { Leccion } from '../../../../types';

export const leccion: Leccion = {
  id: 'mn-04-02',
  titulo: 'Operaciones especiales: potencia, módulo y división entera',
  descripcion: 'Aprende los operadores ** (potencia), % (módulo) y // (división entera).',
  duracionMinutos: 10,
  conceptosClave: ['potencia **', 'módulo %', 'división entera //', 'operadores aritméticos'],
  contenido: [
    { tipo: 'introduccion', texto: 'Además de las operaciones básicas, Python tiene tres operadores muy útiles: la potencia, el módulo (resto) y la división entera. Te permiten hacer cálculos más avanzados.' },
    { tipo: 'explicacion', titulo: 'Potencia **', texto: 'El operador `**` calcula la potencia. Por ejemplo, `2 ** 3` es 2 elevado a la 3, que da 8. Es más legible que usar funciones matemáticas para potencias simples.' },
    { tipo: 'ejemplo', titulo: 'Potencias', descripcion: 'Calculando potencias:', codigo: 'print(2 ** 3)    # 8\nprint(2 ** 10)   # 1024\nprint(10 ** 2)   # 100\nprint(3 ** 4)    # 81' },
    { tipo: 'explicacion', titulo: 'Módulo % — el resto de la división', texto: 'El operador `%` devuelve el resto de la división entera. Por ejemplo, `7 % 3` = 1 porque 7 dividido entre 3 da 2 con resto 1. Es muy útil para saber si un número es par (n % 2 == 0) o impar.' },
    { tipo: 'ejemplo', titulo: 'Módulo', descripcion: 'Trabajando con el resto:', codigo: 'print(17 % 3)  # 2 (17 = 5*3 + 2)\nprint(10 % 2)  # 0 (10 es par)\nprint(7 % 2)   # 1 (7 es impar)' },
    { tipo: 'explicacion', titulo: 'División entera //', texto: 'El operador `//` divide y descarta la parte decimal. Es como hacer una división y quedarte solo con la parte entera.' },
    { tipo: 'ejemplo', titulo: 'División entera', descripcion: 'Comparando / con //:', codigo: 'print(17 / 3)   # 5.666666666666667\nprint(17 // 3)  # 5 (solo la parte entera)\nprint(20 // 6)  # 3' },
    { tipo: 'tabla-visual', titulo: 'Operadores especiales', cabeceras: ['Operador', 'Nombre', 'Ejemplo', 'Resultado'], filras: [['**', 'Potencia', '3 ** 4', '81'], ['%', 'Módulo', '17 % 3', '2'], ['//', 'División entera', '17 // 3', '5']] },
    { tipo: 'resumen', puntos: ['** calcula potencias', '% devuelve el resto de la división', '// divide y descarta decimales', 'Estos operadores son muy usados en programación'] },
  ],
  ejercicios: [
    {
      id: 'mn-04-02-01',
      titulo: 'Potencia',
      descripcion: 'Imprime el resultado de `2 ** 10`.',
      starter: '# Calcula la potencia\n',
      pistas: ["print(2 ** 10)"],
      explicacion: "** es el operador de exponenciación: 2**10 = 1024.",
      solucionOficial: 'print(2 ** 10)',
      validate: { type: 'output', expected: '1024' },
    },
    {
      id: 'mn-04-02-02',
      titulo: 'Módulo (resto)',
      descripcion: 'Imprime el resultado de `17 % 3`.',
      starter: '# Usa el módulo %\n',
      pistas: ["print(17 % 3)"],
      explicacion: "% devuelve el resto de la división. 17 = 5×3 + 2.",
      solucionOficial: 'print(17 % 3)',
      validate: { type: 'output', expected: '2' },
    },
    {
      id: 'mn-04-02-03',
      titulo: 'División entera //',
      descripcion: 'Imprime el resultado de `17 // 3`.',
      starter: '# Usa división entera //\n',
      pistas: ["print(17 // 3)"],
      explicacion: "// devuelve solo la parte entera de la división.",
      solucionOficial: 'print(17 // 3)',
      validate: { type: 'output', expected: '5' },
    },
  ],
  cuestionario: [
    {
      id: 'mn-04-02-q1',
      pregunta: '¿Qué imprime `print(2 ** 8)`?',
      opciones: ['16', '64', '256', '512'],
      correcta: 2,
      explicacion: '2 ** 8 = 2 × 2 × 2 × 2 × 2 × 2 × 2 × 2 = 256.',
    },
    {
      id: 'mn-04-02-q2',
      pregunta: '¿Qué devuelve `10 % 3`?',
      opciones: ['3', '1', '0', '3.33'],
      correcta: 1,
      explicacion: '10 dividido entre 3 da 3 con resto 1, así que 10 % 3 = 1.',
    },
    {
      id: 'mn-04-02-q3',
      pregunta: '¿Qué imprime `print(20 // 6)`?',
      opciones: ['3.33', '3', '4', '2'],
      correcta: 1,
      explicacion: '20 // 6 = 3 (división entera, descarta decimales).',
    },
  ],
};
