import type { Leccion } from '../../../../types';

export const leccion: Leccion = {
  id: 'mn-04-03',
  titulo: 'Funciones matemáticas integradas',
  descripcion: 'Aprende a usar funciones como abs(), round(), max(), min() y sum() para trabajar con números.',
  duracionMinutos: 10,
  conceptosClave: ['abs()', 'round()', 'max()', 'min()', 'sum()', 'funciones integradas'],
  contenido: [
    { tipo: 'introduccion', texto: 'Python viene con muchas funciones matemáticas listas para usar. No necesitas importar nada para usar funciones como `abs()`, `round()`, `max()`, `min()` y `sum()`.' },
    { tipo: 'explicacion', titulo: 'Valor absoluto con abs()', texto: '`abs()` devuelve el valor absoluto de un número, que es su distancia desde cero. Siempre devuelve un número positivo.' },
    { tipo: 'ejemplo', titulo: 'abs() en acción', descripcion: 'El valor absoluto elimina el signo negativo:', codigo: 'print(abs(-42))  # 42\nprint(abs(42))   # 42\nprint(abs(-3.5)) # 3.5' },
    { tipo: 'explicacion', titulo: 'Redondear con round()', texto: '`round()` redondea un número al entero más cercano. También puedes especificar cuántos decimales quieres.' },
    { tipo: 'ejemplo', titulo: 'round() en acción', descripcion: 'Redondeando números:', codigo: 'print(round(3.7))       # 4\nprint(round(3.2))       # 3\nprint(round(3.14159, 2)) # 3.14' },
    { tipo: 'explicacion', titulo: 'Máximo, mínimo y suma', texto: '`max()` encuentra el valor más alto, `min()` el más bajo, y `sum()` suma todos los valores de una lista.' },
    { tipo: 'ejemplo', titulo: 'max, min y sum', descripcion: 'Encontrando valores:', codigo: 'print(max(5, 3, 8, 1))        # 8\nprint(min(5, 3, 8, 1))        # 1\nprint(sum([1, 2, 3, 4, 5]))   # 15' },
    { tipo: 'ejemplo', titulo: 'Promedio con sum y count', descripcion: 'Calculando el promedio manualmente:', codigo: 'numeros = [10, 20, 30]\npromedio = sum(numeros) / len(numeros)\nprint(promedio)  # 20.0' },
    { tipo: 'resumen', puntos: ['abs() da el valor absoluto', 'round() redondea al entero más cercano', 'max() y min() encuentran extremos', 'sum() suma todos los elementos'] },
  ],
  ejercicios: [
    {
      id: 'mn-04-03-01',
      titulo: 'Valor absoluto',
      descripcion: 'Imprime el valor absoluto de `-42` usando `abs()`.',
      starter: '# Usa abs()\n',
      pistas: ["print(abs(-42))"],
      explicacion: "abs() devuelve el valor absoluto (siempre positivo).",
      solucionOficial: 'print(abs(-42))',
      validate: { type: 'output', expected: '42' },
    },
    {
      id: 'mn-04-03-02',
      titulo: 'Redondear round()',
      descripcion: 'Imprime el resultado de `round(3.7)`.',
      starter: '# Redondea 3.7\n',
      pistas: ["print(round(3.7))"],
      explicacion: "round() redondea al entero más cercano.",
      solucionOficial: 'print(round(3.7))',
      validate: { type: 'output', expected: '4' },
    },
    {
      id: 'mn-04-03-03',
      titulo: 'Promedio',
      descripcion: 'Calcula el promedio de `10`, `20` y `30`. Imprime el resultado.',
      starter: '# Calcula y muestra el promedio\n',
      pistas: ["print((10 + 20 + 30) / 3)"],
      explicacion: "El promedio es la suma dividida entre la cantidad.",
      solucionOficial: 'print((10 + 20 + 30) / 3)',
      validate: { type: 'output', expected: '20.0' },
    },
  ],
  cuestionario: [
    {
      id: 'mn-04-03-q1',
      pregunta: '¿Qué imprime `print(abs(-5))`?',
      opciones: ['-5', '5', 'Error', '0'],
      correcta: 1,
      explicacion: 'abs() devuelve el valor absoluto: abs(-5) = 5.',
    },
    {
      id: 'mn-04-03-q2',
      pregunta: '¿Qué imprime `print(max(10, 5, 20, 3))`?',
      opciones: ['3', '10', '20', 'Error'],
      correcta: 2,
      explicacion: 'max() devuelve el valor más alto de los dados.',
    },
    {
      id: 'mn-04-03-q3',
      pregunta: '¿Qué imprime `print(round(3.14159, 2))`?',
      opciones: ['3.1', '3.14', '3.15', '3.14159'],
      correcta: 1,
      explicacion: 'round(3.14159, 2) redondea a 2 decimales: 3.14.',
    },
  ],
};
