import type { Leccion } from '../../../../types';

export const leccion: Leccion = {
  id: 'mn-03-03',
  titulo: 'Métodos de strings',
  descripcion: 'Aprende los métodos más útiles para manipular strings: upper, lower, count, replace, split y más.',
  duracionMinutos: 10,
  conceptosClave: ['métodos de strings', 'upper()', 'lower()', 'count()', 'replace()', 'split()', 'strip()', 'operador in'],
  contenido: [
    { tipo: 'introduccion', texto: 'Los strings tienen métodos integrados que te permiten transformarlos, analizarlos y manipularlos fácilmente. Son como herramientas especializadas para cada tarea con texto.' },
    { tipo: 'explicacion', titulo: 'Métodos de transformación', texto: 'Los métodos `upper()` y `lower()` convierten todo el string a mayúsculas o minúsculas, respectivamente. No modifican el string original, devuelven uno nuevo.' },
    { tipo: 'ejemplo', titulo: 'upper y lower', descripcion: 'Cambiando mayúsculas y minúsculas:', codigo: "print('Python'.upper())  # PYTHON\nprint('PYTHON'.lower())  # python" },
    { tipo: 'explicacion', titulo: 'Búsqueda y conteo', texto: '`count()` cuenta cuántas veces aparece una subcadena. `in` te dice si un string está dentro de otro y devuelve True o False.' },
    { tipo: 'ejemplo', titulo: 'count e in', descripcion: 'Buscando dentro del texto:', codigo: "print('banana'.count('a'))   # 3\nprint('a' in 'banana')       # True\nprint('z' in 'banana')       # False" },
    { tipo: 'explicacion', titulo: 'Reemplazar y limpiar', texto: '`replace(viejo, nuevo)` reemplaza todas las ocurrencias. `strip()` elimina espacios al principio y final.' },
    { tipo: 'ejemplo', titulo: 'replace y strip', descripcion: 'Modificando strings:', codigo: "print('Hola mundo'.replace('mundo', 'Python'))  # Hola Python\nprint('  hola  '.strip())  # hola" },
    { tipo: 'explicacion', titulo: 'Dividir strings', texto: '`split()` divide un string en una lista usando un separador. Es muy útil para procesar datos.' },
    { tipo: 'ejemplo', titulo: 'split', descripcion: 'Dividiendo cadenas:', codigo: "print('a,b,c'.split(','))  # ['a', 'b', 'c']\nprint('uno dos tres'.split())  # ['uno', 'dos', 'tres']" },
    { tipo: 'resumen', puntos: ['upper() y lower() cambian mayúsculas/minúsculas', 'count() cuenta ocurrencias', 'in verifica si un string contiene a otro', 'replace() reemplaza texto', 'strip() elimina espacios', 'split() divide en lista'] },
  ],
  ejercicios: [
    {
      id: 'mn-03-03-01',
      titulo: 'Mayúsculas upper()',
      descripcion: "Usa `print('python'.upper())` para convertir a mayúsculas.",
      starter: "# Convierte a mayúsculas\n",
      pistas: ["print('python'.upper())"],
      explicacion: "upper() convierte todo a mayúsculas.",
      solucionOficial: "print('python'.upper())",
      validate: { type: 'output', expected: 'PYTHON' },
    },
    {
      id: 'mn-03-03-02',
      titulo: 'Reemplazar replace()',
      descripcion: "Usa `print('Hola mundo'.replace('mundo', 'Python'))` para reemplazar.",
      starter: "# Reemplaza\n",
      pistas: ["print('Hola mundo'.replace('mundo', 'Python'))"],
      explicacion: "replace(viejo, nuevo) reemplaza todas las ocurrencias.",
      solucionOficial: "print('Hola mundo'.replace('mundo', 'Python'))",
      validate: { type: 'output', expected: 'Hola Python' },
    },
    {
      id: 'mn-03-03-03',
      titulo: 'Dividir split()',
      descripcion: "Usa `print('a,b,c'.split(','))` para dividir por comas.",
      starter: "# Divide el string\n",
      pistas: ["print('a,b,c'.split(','))"],
      explicacion: "split() divide un string en una lista.",
      solucionOficial: "print('a,b,c'.split(','))",
      validate: { type: 'output', expected: "['a', 'b', 'c']" },
    },
  ],
  cuestionario: [
    {
      id: 'mn-03-03-q1',
      pregunta: "¿Qué imprime `print('HOLA'.lower())`?",
      opciones: ['HOLA', 'hola', 'Hola', 'Error'],
      correcta: 1,
      explicacion: 'lower() convierte todo a minúsculas.',
    },
    {
      id: 'mn-03-03-q2',
      pregunta: "¿Qué imprime `print('Ana'.count('a'))`?",
      opciones: ['0', '1', '2', 'Error'],
      correcta: 1,
      explicacion: 'count distingue mayúsculas: "Ana" tiene una "a" minúscula y una "A" mayúscula.',
    },
    {
      id: 'mn-03-03-q3',
      pregunta: "¿Qué imprime `print('  x  '.strip())`?",
      opciones: ['  x  ', 'x', 'x  ', '  x'],
      correcta: 1,
      explicacion: 'strip() elimina espacios de ambos lados.',
    },
  ],
};
