import type { Leccion } from '../../../../types';

export const leccion: Leccion = {
  id: 'mn-03-01',
  titulo: 'Introducción a los Strings',
  descripcion: 'Aprende a trabajar con cadenas de texto: crearlas, concatenarlas y medir su longitud.',
  duracionMinutos: 10,
  conceptosClave: ['strings', 'concatenación', 'len()', 'comillas simples y dobles'],
  contenido: [
    { tipo: 'introduccion', texto: 'Los strings (cadenas de texto) son uno de los tipos de datos más usados en Python. Sirven para representar texto: nombres, mensajes, direcciones, ¡lo que quieras!' },
    { tipo: 'explicacion', titulo: 'Crear strings', texto: 'Puedes crear strings usando comillas simples `\'...\'` o dobles `"..."`. Ambas funcionan igual. La ventaja de tener dos tipos es que puedes incluir un tipo de comilla dentro del otro.' },
    { tipo: 'ejemplo', titulo: 'Strings básicos', descripcion: 'Diferentes formas de crear strings:', codigo: "saludo = 'Hola'\nnombre = \"Ana\"\nfrase = \"Ella dijo: 'Hola'\"\nprint(saludo, nombre, frase)" },
    { tipo: 'explicacion', titulo: 'Concatenar strings', texto: 'Puedes unir strings usando el operador `+`. Esto se llama concatenación. También puedes repetir un string multiplicándolo por un número.' },
    { tipo: 'ejemplo', titulo: 'Concatenación y repetición', descripcion: 'Uniendo y repitiendo strings:', codigo: "print('Hola' + ' ' + 'Mundo')  # Hola Mundo\nprint('ha' * 3)               # hahaha" },
    { tipo: 'explicacion', titulo: 'Medir strings con len()', texto: 'La función `len()` devuelve la cantidad de caracteres en un string, incluyendo espacios y signos de puntuación.' },
    { tipo: 'ejemplo', titulo: 'Usando len()', descripcion: 'Midiendo la longitud de strings:', codigo: "print(len('Python'))  # 6\nprint(len(''))        # 0\nprint(len('Hola Mundo'))  # 10" },
    { tipo: 'resumen', puntos: ['Los strings se crean con comillas simples o dobles', '+ concatena strings, * los repite', 'len() cuenta los caracteres del string', 'Puedes anidar comillas si alternas simples y dobles'] },
  ],
  ejercicios: [
    {
      id: 'mn-03-01-01',
      titulo: 'Concatenar strings',
      descripcion: "Usa `print('Hola' + ' ' + 'Mundo')` para concatenar strings.",
      starter: '# Concatena los strings\n',
      pistas: ["print('Hola' + ' ' + 'Mundo')"],
      explicacion: "El operador + une strings.",
      solucionOficial: "print('Hola' + ' ' + 'Mundo')",
      validate: { type: 'output', expected: 'Hola Mundo' },
    },
    {
      id: 'mn-03-01-02',
      titulo: 'Longitud con len()',
      descripcion: "Usa `print(len('Python'))` para ver cuántas letras tiene.",
      starter: "# Usa len() para contar letras\n",
      pistas: ["print(len('Python'))"],
      explicacion: "len() devuelve la cantidad de caracteres.",
      solucionOficial: "print(len('Python'))",
      validate: { type: 'output', expected: '6' },
    },
    {
      id: 'mn-03-01-03',
      titulo: 'Repetir string',
      descripcion: "Usa `print('ha' * 3)` para repetir el string tres veces.",
      starter: "# Repite el string\n",
      pistas: ["print('ha' * 3)"],
      explicacion: "* repite un string N veces.",
      solucionOficial: "print('ha' * 3)",
      validate: { type: 'output', expected: 'hahaha' },
    },
  ],
  cuestionario: [
    {
      id: 'mn-03-01-q1',
      pregunta: '¿Qué imprime `print(len("abc"))`?',
      opciones: ['2', '3', '4', 'Error'],
      correcta: 1,
      explicacion: 'len() cuenta los caracteres: "abc" tiene 3.',
    },
    {
      id: 'mn-03-01-q2',
      pregunta: '¿Qué imprime `print("a" + "b")`?',
      opciones: ['a b', 'ab', "'ab'", 'Error'],
      correcta: 1,
      explicacion: 'El operador + concatena: "a" + "b" = "ab".',
    },
    {
      id: 'mn-03-01-q3',
      pregunta: '¿Qué imprime `print("¡" * 3)`?',
      opciones: ['¡3', '¡¡¡', '¡*3', 'Error'],
      correcta: 1,
      explicacion: '* repite el string: "¡" * 3 = "¡¡¡".',
    },
  ],
};
