import type { Leccion } from '../../../../types';

export const leccion: Leccion = {
  id: 'mn-03-02',
  titulo: 'Indexación y slicing de strings',
  descripcion: 'Aprende a acceder a caracteres individuales y a extraer porciones de un string.',
  duracionMinutos: 10,
  conceptosClave: ['índices', 'indexación', 'slicing', 'strings', 'inmutabilidad'],
  contenido: [
    { tipo: 'introduccion', texto: 'Los strings son secuencias de caracteres, y puedes acceder a cada uno de ellos por su posición. También puedes extraer porciones completas usando slicing. Es como poder cortar tu texto en rodajas.' },
    { tipo: 'explicacion', titulo: 'Indexación — acceder por posición', texto: 'Cada carácter en un string tiene un número de índice. El primer carácter está en la posición 0, el segundo en la 1, y así sucesivamente. También puedes usar índices negativos para contar desde el final.' },
    { tipo: 'tabla-visual', titulo: 'Índices de "Python"', cabeceras: ['Carácter', 'P', 'y', 't', 'h', 'o', 'n'], filas: [['Índice +', '0', '1', '2', '3', '4', '5'], ['Índice -', '-6', '-5', '-4', '-3', '-2', '-1']] },
    { tipo: 'ejemplo', titulo: 'Acceso por índice', descripcion: 'Obteniendo caracteres individuales:', codigo: "texto = 'Python'\nprint(texto[0])  # P\nprint(texto[2])  # t\nprint(texto[-1])  # n" },
    { tipo: 'explicacion', titulo: 'Slicing [inicio:fin]', texto: 'El slicing extrae una porción del string. Usa la sintaxis `texto[inicio:fin]`. El inicio se incluye, el fin se excluye. Si omites inicio, empieza desde 0. Si omites fin, llega hasta el final.' },
    { tipo: 'ejemplo', titulo: 'Slicing en acción', descripcion: 'Extrayendo porciones:', codigo: "texto = 'Python'\nprint(texto[0:3])  # Pyt\nprint(texto[3:])   # hon\nprint(texto[:3])   # Pyt\nprint(texto[::-1]) # nohtyP (invertido)" },
    { tipo: 'nota', texto: 'El slicing con `[::-1]` invierte cualquier string. Es un truco muy útil en Python.' },
    { tipo: 'resumen', puntos: ['Los índices empiezan en 0', 'texto[-1] accede al último carácter', 'texto[inicio:fin] extrae una porción', 'texto[::-1] invierte el string'] },
  ],
  ejercicios: [
    {
      id: 'mn-03-02-01',
      titulo: 'Primer carácter',
      descripcion: "Crea `texto = 'El Broncas'`. Imprime `texto[0]` para obtener el primer carácter.",
      starter: "texto = 'El Broncas'\n# Imprime el primer carácter\n",
      pistas: ["print(texto[0])"],
      explicacion: "Los índices en Python empiezan en 0.",
      solucionOficial: "texto = 'El Broncas'\nprint(texto[0])",
      validate: { type: 'output', expected: 'E' },
    },
    {
      id: 'mn-03-02-02',
      titulo: 'Último carácter',
      descripcion: "Crea `texto = 'Python'`. Imprime `texto[-1]` para obtener el último carácter.",
      starter: "texto = 'Python'\n# Imprime el último carácter\n",
      pistas: ["print(texto[-1])"],
      explicacion: "El índice -1 accede al último elemento.",
      solucionOficial: "texto = 'Python'\nprint(texto[-1])",
      validate: { type: 'output', expected: 'n' },
    },
    {
      id: 'mn-03-02-03',
      titulo: 'Slice de string',
      descripcion: "Crea `texto = 'Python'`. Imprime `texto[0:3]` para obtener los primeros 3 caracteres.",
      starter: "texto = 'Python'\n# Imprime los primeros 3 caracteres\n",
      pistas: ["print(texto[0:3])"],
      explicacion: "[inicio:fin] extrae una porción del string.",
      solucionOficial: "texto = 'Python'\nprint(texto[0:3])",
      validate: { type: 'output', expected: 'Pyt' },
    },
  ],
  cuestionario: [
    {
      id: 'mn-03-02-q1',
      pregunta: "¿Qué imprime `print('ABCDEF'[2])`?",
      opciones: ['B', 'C', 'D', 'Error'],
      correcta: 1,
      explicacion: 'El índice 2 es el tercer carácter: "C" (A=0, B=1, C=2).',
    },
    {
      id: 'mn-03-02-q2',
      pregunta: "¿Qué imprime `print('ABCDEF'[-1])`?",
      opciones: ['A', 'F', 'Error', 'Nada'],
      correcta: 1,
      explicacion: '-1 accede al último carácter: "F".',
    },
    {
      id: 'mn-03-02-q3',
      pregunta: "¿Qué hace `[::-1]` en un string?",
      opciones: ['Lo divide en dos', 'Lo invierte', 'Lo convierte en lista', 'Elimina los espacios'],
      correcta: 1,
      explicacion: '[::-1] recorre el string de atrás hacia adelante, invirtiéndolo.',
    },
  ],
};
