import type { Leccion } from '../../../../types';

export const leccion: Leccion = {
  id: 'mn-01-02',
  titulo: 'Imprimiendo números y operaciones',
  descripcion: 'Aprende a imprimir números y a realizar operaciones matemáticas dentro de print().',
  duracionMinutos: 10,
  conceptosClave: ['print() con números', 'operadores aritméticos', 'suma', 'resta', 'multiplicación', 'división'],
  contenido: [
    { tipo: 'introduccion', texto: '`print()` no solo sirve para texto, también puedes imprimir números y hasta hacer cálculos directamente dentro de la función. Así Python puede funcionar como una calculadora.' },
    { tipo: 'explicacion', titulo: 'Números en print()', texto: 'Los números enteros y decimales se pueden imprimir sin comillas. Python los reconoce como valores numéricos directamente.' },
    { tipo: 'ejemplo', titulo: 'Imprimir números', descripcion: 'Puedes imprimir cualquier número directamente:', codigo: 'print(42)\nprint(3.14)\nprint(-7)' },
    { tipo: 'explicacion', titulo: 'Operaciones dentro de print()', texto: 'Puedes hacer cálculos directamente dentro de `print()`. Python primero resuelve la operación y luego imprime el resultado.' },
    { tipo: 'ejemplo', titulo: 'Suma, resta, multiplicación y división', descripcion: 'Operaciones aritméticas básicas:', codigo: "print(2 + 2)    # 4\nprint(10 - 3)   # 7\nprint(5 * 8)    # 40\nprint(10 / 2)   # 5.0" },
    { tipo: 'nota', texto: 'En Python 3, la división con `/` siempre devuelve un número decimal (float), incluso si la división es exacta.' },
    { tipo: 'error-comun', titulo: 'Operador incorrecto', codigoMal: "print(10 x 2)", problema: 'En Python no se usa `x` para multiplicar, sino `*`.', codigoBien: 'print(10 * 2)', solucion: 'Usa `*` para multiplicación. El signo `x` no existe en Python.' },
    { tipo: 'resumen', puntos: ['Los números en print() no llevan comillas', 'Puedes hacer operaciones matemáticas dentro de print()', '+ suma, - resta, * multiplica, / divide', 'La división / siempre da resultado decimal'] },
  ],
  ejercicios: [
    {
      id: 'mn-01-02-01',
      titulo: 'Suma con print',
      descripcion: 'Usa `print()` para mostrar el resultado de `2 + 2`.',
      starter: '# Escribe tu código aquí\n',
      pistas: ["`print(2 + 2)`"],
      explicacion: "Python puede calcular operaciones directamente dentro de print().",
      solucionOficial: 'print(2 + 2)',
      validate: { type: 'output', expected: '4' },
    },
    {
      id: 'mn-01-02-02',
      titulo: 'Multiplicación',
      descripcion: 'Usa `print()` para mostrar el resultado de `5 * 8`.',
      starter: '# Escribe tu código aquí\n',
      pistas: ["`print(5 * 8)`"],
      explicacion: "El asterisco * es el operador de multiplicación en Python.",
      solucionOficial: 'print(5 * 8)',
      validate: { type: 'output', expected: '40' },
    },
    {
      id: 'mn-01-02-03',
      titulo: 'División',
      descripcion: 'Usa `print()` para mostrar el resultado de `10 / 2`.',
      starter: '# Escribe tu código aquí\n',
      pistas: ["`print(10 / 2)` — el resultado será 5.0, no 5"],
      explicacion: "La división / siempre retorna float en Python 3.",
      solucionOficial: 'print(10 / 2)',
      validate: { type: 'output', expected: '5.0' },
    },
  ],
  cuestionario: [
    {
      id: 'mn-01-02-q1',
      pregunta: '¿Qué imprime print(3 + 4)?',
      opciones: ['34', "'7'", '7', 'Error'],
      correcta: 2,
      explicacion: 'Python suma 3 + 4 y da 7, luego lo imprime.',
    },
    {
      id: 'mn-01-02-q2',
      pregunta: '¿Qué operador se usa para multiplicar en Python?',
      opciones: ['x', '*', '·', 'mul'],
      correcta: 1,
      explicacion: 'El asterisco * es el operador de multiplicación.',
    },
    {
      id: 'mn-01-02-q3',
      pregunta: '¿Qué imprime print(10 / 4)?',
      opciones: ['2', '2.5', '2.0', 'Error'],
      correcta: 1,
      explicacion: 'La división / en Python 3 siempre devuelve float: 2.5.',
    },
  ],
};
