import type { Leccion } from '../../../../types';

export const leccion: Leccion = {
  id: 'mn-06-03',
  titulo: 'Combinaciones avanzadas de print()',
  descripcion: 'Combina sep, end y caracteres especiales para crear salidas formateadas complejas.',
  duracionMinutos: 10,
  conceptosClave: ['combinar sep y end', 'formato de salida', 'repetición de strings', 'problemas prácticos'],
  contenido: [
    { tipo: 'introduccion', texto: 'Ahora que conoces sep, end y los caracteres especiales, puedes combinarlos para crear salidas con formato profesional.' },
    { tipo: 'explicacion', titulo: 'Combinando sep y end', texto: 'Puedes usar sep y end juntos en el mismo print() para controlar completamente el formato de salida.' },
    { tipo: 'ejemplo', titulo: 'sep y end juntos', descripcion: 'Usando ambos parámetros:', codigo: "print(1, 2, 3, sep=' | ', end=' FIN\\n')\n# 1 | 2 | 3 FIN" },
    { tipo: 'explicacion', titulo: 'Crear líneas decorativas', texto: 'Puedes multiplicar strings para crear líneas decorativas, separadores visuales, o tablas simples.' },
    { tipo: 'ejemplo', titulo: 'Decoración con print', descripcion: 'Líneas y separadores:', codigo: "print('=' * 20)\nprint('MI PROGRAMA')\nprint('=' * 20)\nprint('*' * 30)\nprint('-' * 20)" },
    { tipo: 'explicacion', titulo: 'Tablas simples sin formato avanzado', texto: 'Combinando \\t y print() puedes crear tabulas básicas.' },
    { tipo: 'ejemplo', titulo: 'Tabla simple', descripcion: 'Datos en columnas:', codigo: "print('Producto\\tPrecio\\tCant')\nprint('Manzana\\t1.20\\t10')\nprint('Pan\\t0.80\\t5')\nprint('-' * 20)" },
    { tipo: 'nota', texto: 'Más adelante aprenderás f-strings, que dan mucho más control sobre el formato. Por ahora, estas técnicas son suficientes.' },
    { tipo: 'resumen', puntos: ['Puedes combinar sep y end en un mismo print()', 'Multiplicar strings crea líneas decorativas', '\\n y \\t ayudan a estructurar la salida', 'Estas técnicas son la base del formateo en Python'] },
  ],
  ejercicios: [
    {
      id: 'mn-06-03-01',
      titulo: 'sep con pipe',
      descripcion: "Usa `print(1, 2, 3, sep=' | ')` para separar con pipe.",
      starter: "# Usa sep=' | '\n",
      pistas: ["print(1, 2, 3, sep=' | ')"],
      explicacion: "sep puede ser cualquier string.",
      solucionOficial: "print(1, 2, 3, sep=' | ')",
      validate: { type: 'output', expected: '1 | 2 | 3' },
    },
    {
      id: 'mn-06-03-02',
      titulo: 'Sin salto de línea',
      descripcion: "Imprime `1`, `2` y `3` en la misma línea sin espacios: `123`",
      starter: '# Imprime 123 en una sola línea\n',
      pistas: ["print('1', end='')\nprint('2', end='')\nprint('3')"],
      explicacion: "end='' elimina el separador.",
      solucionOficial: "print('1', end='')\nprint('2', end='')\nprint('3')",
      validate: { type: 'output', expected: '123' },
    },
    {
      id: 'mn-06-03-03',
      titulo: 'Línea de guiones',
      descripcion: "Usa `print('-' * 20)` para imprimir 20 guiones.",
      starter: '# Imprime 20 guiones\n',
      pistas: ["print('-' * 20)"],
      explicacion: "Multiplicar un string por un número lo repite.",
      solucionOficial: "print('-' * 20)",
      validate: { type: 'output', expected: '--------------------' },
    },
  ],
  cuestionario: [
    {
      id: 'mn-06-03-q1',
      pregunta: "¿Qué imprime `print('X', 'Y', sep='=')`?",
      opciones: ['X=Y', 'X Y', 'X= Y', 'X=Y='],
      correcta: 0,
      explicacion: "sep='=' separa los valores con =: X=Y.",
    },
    {
      id: 'mn-06-03-q2',
      pregunta: "¿Qué imprime `print('#' * 5)`?",
      opciones: ['#####', '#5', '5#', '#####5'],
      correcta: 0,
      explicacion: "'#' * 5 repite el # cinco veces: #####.",
    },
    {
      id: 'mn-06-03-q3',
      pregunta: "¿Cómo imprimirías '1-2-3' con un solo print?",
      opciones: ["print('1-2-3')", "print(1, 2, 3, sep='-')", "print(1-2-3)", "print('1', '2', '3', end='-')"],
      correcta: 1,
      explicacion: "sep='-' separa los valores 1, 2 y 3 con guiones.",
    },
  ],
};
