import type { Insignia } from '../types';

export const INSIGNIAS: Insignia[] = [
  {
    id: 'primer-paso',
    nombre: 'Primer Paso',
    descripcion: 'Completaste tu primera lección',
    icono: '🌱',
    condicion: 'Completa 1 lección',
  },
  {
    id: 'en-racha',
    nombre: 'En Racha',
    descripcion: 'Estudiaste 3 días consecutivos',
    icono: '🔥',
    condicion: 'Mantén racha de 3 días',
  },
  {
    id: 'relampago',
    nombre: 'Relámpago',
    descripcion: 'Estudiaste 5 días consecutivos',
    icono: '⚡',
    condicion: 'Mantén racha de 5 días',
  },
  {
    id: 'constancia',
    nombre: 'Constancia',
    descripcion: 'Estudiaste 10 días consecutivos',
    icono: '💎',
    condicion: 'Mantén racha de 10 días',
  },
  {
    id: 'punteria',
    nombre: 'Puntería',
    descripcion: 'Resolviste 10 ejercicios en el primer intento',
    icono: '🎯',
    condicion: 'Resuelve 10 ejercicios al primer intento',
  },
  {
    id: 'sin-pistas',
    nombre: 'Sin Pistas',
    descripcion: 'Resolviste 20 ejercicios sin usar pistas',
    icono: '🧠',
    condicion: 'Resuelve 20 ejercicios sin ver pistas',
  },
  {
    id: 'estudioso',
    nombre: 'Estudioso',
    descripcion: 'Completaste 50 ejercicios del banco',
    icono: '📚',
    condicion: 'Completa 50 ejercicios del banco',
  },
  {
    id: 'coleccionista',
    nombre: 'Coleccionista',
    descripcion: 'Completaste 200 ejercicios del banco',
    icono: '🌟',
    condicion: 'Completa 200 ejercicios del banco',
  },
  {
    id: 'muy-novato-graduado',
    nombre: 'Muy Novato Graduado',
    descripcion: 'Completaste el nivel Muy Novato',
    icono: '🏆',
    condicion: 'Completa el 100% del nivel Muy Novato',
  },
  {
    id: 'novato-graduado',
    nombre: 'Novato Graduado',
    descripcion: 'Completaste el nivel Novato',
    icono: '⭐',
    condicion: 'Completa el 100% del nivel Novato',
  },
  {
    id: 'intermedio-graduado',
    nombre: 'Intermedio Graduado',
    descripcion: 'Completaste el nivel Intermedio',
    icono: '🚀',
    condicion: 'Completa el 100% del nivel Intermedio',
  },
  {
    id: 'maestro-python',
    nombre: 'Maestro Python',
    descripcion: 'Completaste el nivel Avanzado',
    icono: '👑',
    condicion: 'Completa el 100% del nivel Avanzado',
  },
  {
    id: 'certificado',
    nombre: 'Certificado Python',
    descripcion: 'Completaste los 4 niveles al 100%',
    icono: '🎓',
    condicion: 'Completa los 4 niveles al 100%',
  },
];
